version: '3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer
    ports:
      - "3307:3306"
    volumes:
      - C:\Users\breno\sqlfile:/docker-entrypoint-initdb.d

  app:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: qwer
      DB_NAME: claudio2022
      DB_PORT: 3306
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db_data: